### ISSUE TITLE
Using the default QoS yaml throws an error when playing the bag

### ISSUE THREAD

**Issue by geoeo** [ros2/rosbag2#1125]
## Description
Using the default QoS yaml on this site throws an error

### Expected Behavior
Using the default QoS Yaml given in the Readme.md as a offered_qos_profiles argument does not result in a crash when playing the bag

### Actual Behavior
Currently when using the default QoS Yaml I get a crash when playing my recorded bag `yaml-cpp: error at line 1, column 1: bad conversion`

## To Reproduce
1.Copy the QoS yaml and use it as `offered_qos_profiles`
2. Record your bag
3. replay the bag via `ros2 bag play ..`
4. An error is given in the terminal `yaml-cpp: error at line 1, column 1: bad conversion`

## System (please complete the following information)
 - OS: Ubuntu Jammy
 - ROS 2 Distro: Humble/Rolling
 - Version: apt-version tested on 14.10.22

## Additional context
** Add any other context about the problem here **

**Comment by MichaelOrlov** [comment]
@geoeo Could you please attach your QoS yaml which is giving error on playback?

**Comment by geoeo** [comment]
This is the vanilla file I tried which is published on the readme page

```
/topic_name:
  history: keep_last
  depth: 10
  reliability: reliable
  durability: volatile
  deadline:
    # unspecified/infinity
    sec: 0
    nsec: 0
  lifespan:
    # unspecified/infinity
    sec: 0
    nsec: 0
  liveliness: system_default
  liveliness_lease_duration:
    # unspecified/infinity
    sec: 0
    nsec: 0
  avoid_ros_namespace_conventions: false
  ```
  I also tried chaning `/topic_name:` to `/tf_static:` 
  
  Its set via the `offered_qos_profiles` attribute when creating `TopicMetadata` (via python).
