### ISSUE TITLE
Possible data loss in case of large amount of topics and high publishing frequency

### ISSUE THREAD

**Issue by gtep96** [ros2/rosbag2#1430]
## Description
I've encountered a data loss when using the ROS2 bag recording: i have ~20 publishers with publishing frequency 1000 msgs/sec per topic, and first several messages could be lost during the initial recording phase. This problem results in missing data at the beginning of the bag file. 

### Expected Behavior
The ROS2 bag recording should start capturing data immediately upon execution, and the recorded bag file should contain all relevant data from the beginning of the recording session. Is there any limitations on amount of topics/publishing frequency/data size per message for a bag recorder?

### Actual Behavior
Upon initiating the ROS2 bag recording, it takes some time before data is captured in the bag file. As a result, the initial moments of data are not properly recorded.

## To Reproduce
1. Run `ros2 bag record --all`
2. Launch a node with many (20 in my case) publishers with a timer period = 1/1000
3. Observe the recorded bag file and check for missing data at the beginning of the file.

## System (please complete the following information)
 - OS: Ubuntu 20.04 (inside Docker dev container)
 - ROS 2 Distro: Humble
 - Version: release

## Additional context
I've tried to run rosbag2 with `--include-unpublished-topics`, but with no success, it still can lose some msgs.
Running with `--no-discovery` with specified topics names leads to empty bag:
```yaml

rosbag2_bagfile_information:
  version: 5
  storage_identifier: sqlite3
  duration:
    nanoseconds: 0
  starting_time:
    nanoseconds_since_epoch: 9223372036854775807
  message_count: 0
  topics_with_message_count:
    []
  compression_format: ""
  compression_mode: ""
  relative_file_paths:
    - rosbag2_2023_07_23-12_55_55_0.db3
  files:
    - path: rosbag2_2023_07_23-12_55_55_0.db3
      starting_time:
        nanoseconds_since_epoch: 9223372036854775807
      duration:
        nanoseconds: 0
      message_count: 0

```

Is there a way to initialize rosbag2 in advance or how can I solve this problem?
