### ISSUE TITLE
QoS override YAML parsing different between Python & C++

### ISSUE THREAD

**Issue by roncapat** [ros2/rosbag2#1475]
When parsing QoS override file from Python:
[ros2bag/ros2bag/api/\_\_init\_\_.py](https://github.com/ros2/rosbag2/blob/a80adfda6678185c7605fd3820ab3a67469e2d8d/ros2bag/ros2bag/api/__init__.py)

``` python3
# This map needs to be updated when new policies are introduced
_QOS_POLICY_FROM_SHORT_NAME = {
    'history': QoSHistoryPolicy.get_from_short_key,
    'reliability': QoSReliabilityPolicy.get_from_short_key,
    'durability': QoSDurabilityPolicy.get_from_short_key,
    'liveliness': QoSLivelinessPolicy.get_from_short_key
}
_DURATION_KEYS = ['deadline', 'lifespan', 'liveliness_lease_duration']
_VALUE_KEYS = ['depth', 'avoid_ros_namespace_conventions']

...

def interpret_dict_as_qos_profile(qos_profile_dict: Dict) -> QoSProfile:
    """Sanitize a user provided dict of a QoS profile and verify all keys are valid."""
    new_profile_dict = {}
    for policy_key, policy_value in qos_profile_dict.items():
        if policy_key in _DURATION_KEYS:
            new_profile_dict[policy_key] = dict_to_duration(policy_value)
        elif policy_key in _QOS_POLICY_FROM_SHORT_NAME:
            new_profile_dict[policy_key] = _QOS_POLICY_FROM_SHORT_NAME[policy_key](policy_value)
        elif policy_key in _VALUE_KEYS:
            if policy_value < 0:
                raise ValueError('`{}` may not be a negative value.'.format(policy_key))
            new_profile_dict[policy_key] = policy_value
        else:
            raise ValueError('Unexpected key `{}` for QoS profile.'.format(policy_key))
    return QoSProfile(**new_profile_dict)
```
params like `history` is parsed for strings like `keep_all` or `keep_last`.

In fact, the CLI documentation [here](https://docs.ros.org/en/iron/How-To-Guides/Overriding-QoS-Policies-For-Recording-And-Playback.html) defines the YAML schema as:
```
history: [keep_all, keep_last]
depth: int
reliability: [system_default, reliable, best_effort, unknown]
durability: [system_default, transient_local, volatile, unknown]
deadline:
  sec: int
  nsec: int
lifespan:
  sec: int
  nsec: int
liveliness: [system_default, automatic, manual_by_topic, unknown]
liveliness_lease_duration:
  sec: int
  nsec: int
avoid_ros_namespace_conventions: [true, false]
```

However, the `rosbag2_transport/src/rosbag2_transport/qos.cpp` handles `history/durability/reliability/liveliness` as plain integers:
```c++
bool convert<rosbag2_transport::Rosbag2QoS>::decode(
  const Node & node, rosbag2_transport::Rosbag2QoS & qos)
{
  auto history = static_cast<rmw_qos_history_policy_t>(node["history"].as<int>());
  auto reliability = static_cast<rmw_qos_reliability_policy_t>(node["reliability"].as<int>());
  auto durability = static_cast<rmw_qos_durability_policy_t>(node["durability"].as<int>());
  auto liveliness = static_cast<rmw_qos_liveliness_policy_t>(node["liveliness"].as<int>());

...
```

This even seems to be acknowledged by [rosbag2_transport/test/rosbag2\_transport/test\_qos.cpp](https://github.com/ros2/rosbag2/blob/a80adfda6678185c7605fd3820ab3a67469e2d8d/rosbag2_transport/test/rosbag2_transport/test_qos.cpp)
```c++
  // This test shows how this data looks at the time of introduction
  // Bags created by this version of rosbag2 look like this and must be able to be read
  std::string serialized_profiles =
    "- history: 1\n"
    "  depth: 10\n"
    "  reliability: 1\n"
    "  durability: 2\n"
    "  deadline:\n"
    "    sec: 0\n"
    "    nsec: 0\n"
    "  lifespan:\n"
    "    sec: 0\n"
    "    nsec: 0\n"
    "  liveliness: 0\n"
    "  liveliness_lease_duration:\n"
    "    sec: 0\n"
    "    nsec: 0\n"
    "  avoid_ros_namespace_conventions: false\n";
```

Making C++ YAML encode/decode of QoS overrides to comply with the YAML schema above is a prerequisite of #902 #1419.

@MichaelOrlov do you agree on this? May I open a dedicated PR?
