### ISSUE TITLE
param set uri doesn't work for Player component

### ISSUE THREAD

**Issue by KenYN** [ros2/rosbag2#1508]
- Relates #1419 

## Description
With the new component Player, I cannot change the file to play back

### Expected Behavior
Given this YAML file:
```
launch:
    - node_container:
        pkg: rclcpp_components
        exec: component_container
        name: my_container
        namespace: ''
        composable_node:
            -   pkg: rosbag2_transport
                plugin: rosbag2_transport::Player
                name: bag_player
                namespace: ''
                param:
                    - name: uri
                      value: '/path/to/file1/'
```
Then the following commands:
```
$ ros2 param set /bag_player uri "/path/to/file2"
$ ros2 service call /bag_player/play rosbag2_interfaces/srv/Play "{start_offset: {sec: 0, nanosec: 0}, playback_duration: {sec: 65535, nanosec: 0}, playback_until_timestamp: {sec: 0, nanosec: 0}}"
```
(Note, `Play` doesn't seem to have a `play_to_end` value)

Should result in `file2` being played back.

### Actual Behavior
`file1` is played back, even though:
```
$ ros2 param get /bag_player uri
String value is: /path/to/file2
```

## To Reproduce
See above

## System (please complete the following information)
 - OS: Ubuntu 22.04
 - ROS 2 Distro: rolling
 - Install Method: source
 - Version: patch-2
