### ISSUE TITLE
Fix double output when playing with --clock in rosbag containing clock

### ISSUE THREAD

**Issue by kosuke55** [ros2/rosbag2#1645]
## Description

If we play rosbag containing `/clock` with the -`-clock` option, we will get double `/clock` output.

```
ros2 topic echo /clock

---
clock:
  sec: 1715138101
  nanosec: 880998015
---
clock:
  sec: 1666578700
  nanosec: 606046430
---
clock:
  sec: 1666578700
  nanosec: 608539499
---
clock:
  sec: 1715138101
  nanosec: 891000787
---
clock:
  sec: 1666578700
  nanosec: 611041316
```

## Completion Criteria

only one `/clock` is published

## Implementation Notes / Suggestions

If `--clock` is specified, how about excluding `/clock?` (https://github.com/ros2/rosbag2/pull/1646)
```
        if play_options.clock_publish_frequency > 0:
            play_options.exclude_topics_to_filter.append('/clock')
```

## Testing Notes / Suggestions

play rosbag containing `/clock` with `--clock`
