### ISSUE TITLE
Ros bag reindex failed to generate topic inside metadata.yaml if the message_count is 0

### ISSUE THREAD

**Issue by KoolElmout** [ros2/rosbag2#1719]
## Description
On re-indexing a sqllite3 rosbag which originally contains a topic with 0 data inside (message_count:0), the metadata.yaml is not generated properly. The full topic is absent. 

This bug was discovered using the python Teranis rosbags reader's library.  (Confer https://gitlab.com/ternaris/rosbags/-/issues/91). 

### Expected Behavior
The reindex rosbag 's metadata.yaml file shall contains the topic with message_count:0
eg:

```
    - topic_metadata:
        name: /tract/control_signals
        type:msgs/msg/ControlSignal
        serialization_format: cdr
        offered_qos_profiles: "- history: 3\n  depth: 0\n  reliability: 1\n  durability: 2\n  deadline:\n    sec: 9223372036\n    nsec: 854775807\n  lifespan:\n    sec: 9223372036\n    nsec: 854775807\n  liveliness: 1\n  liveliness_lease_duration:\n    sec: 9223372036\n    nsec: 854775807\n  avoid_ros_namespace_conventions: false"
      message_count: 0  

```

### Actual Behavior
Actually, the full topic section is not present after re-index.

## To Reproduce
1) Take a sqlite bag with at least a topic which has a message_count at 0. 
2) Remove the metadata.yaml 
3) Launch the command
`ros2 bag reindex -s sqlite3  mybag
`
4) Check the generated metadata.yaml, all topics with 0 message count have disappeared. 

PS: This permit to re-generate the problem. In the true world, it shall permit to generate the metadata.yaml in case it has not been generated (which happens several time a day in my case.) 

## System (please complete the following information)
 - OS: [e.g. Ubuntu 22.04]
 - ROS 2 Distro: [Humble]
 - Install Method: [APT, release ]
 - Version: ros-humble-ros2bag                                0.15.9-1jammy.20240217.104352           amd6
 
## Additional context
If we place back from the original data to the re-indexed one the topic section, the python Teranis rosbags reader's library read the file properly. If not it failed. We conclude that the information shall be present inside the db3 but not reported in metadata.yaml.
