### ISSUE TITLE
ros2 bag convert data loss with message compression mode

### ISSUE THREAD

**Issue by DangitBen** [ros2/rosbag2#1973]
## Description
`ros2 bag convert` has data loss when converting to a bag using `compression_mode: message`

### Expected Behavior

- The compressed and uncompressed versions of bags should contain the same messages.
- `ros2 bag info uncompressed`, `ros2 bag info compressed-message`, and `ros2 bag info compressed-file` should output the same message counts for each topic 

### Actual Behavior

```bash
$ ros2 bag info uncompressed

Files:             uncompressed_0.mcap
Bag size:          4.9 KiB
Storage id:        mcap
ROS Distro:        jazzy
Duration:          0.000000029s
Start:             Dec 31 1969 18:00:00.000000000 (0.000000000)
End:               Dec 31 1969 18:00:00.000000029 (0.000000029)
Messages:          30
Topic information: Topic: /strings | Type: std_msgs/msg/String | Count: 30 | Serialization Format: cdr
Service:           0
Service information:
```

Example output I received: 
```bash
$ ros2 bag info compressed-file

Files:             compressed-file_0.mcap.zstd
Bag size:          1.8 KiB
Storage id:        mcap
ROS Distro:        jazzy
Duration:          0.000000029s
Start:             Dec 31 1969 18:00:00.000000000 (0.000000000)
End:               Dec 31 1969 18:00:00.000000029 (0.000000029)
Messages:          30 # looks good!
Topic information: Topic: /strings | Type: std_msgs/msg/String | Count: 30 | Serialization Format: cdr
Service:           0
Service information:
```
So far so good for file compression mode. But message compression mode has a problem: 

```bash
$ ros2 bag info compressed-message

Files:             compressed-message_0.mcap
Bag size:          5.1 KiB
Storage id:        mcap
ROS Distro:        jazzy
Duration:          0.000000029s
Start:             Dec 31 1969 18:00:00.000000000 (0.000000000)
End:               Dec 31 1969 18:00:00.000000029 (0.000000029)
Messages:          28 # oh no
Topic information: Topic: /strings | Type: std_msgs/msg/String | Count: 28 | Serialization Format: cdr
Service:           0
Service information:
```

Number of messages dropped is inconsistent between attempts. Here is the output after attempting the conversion again clean:
```bash
$ ros2 bag info compressed-message

Files:             compressed-message_0.mcap
Bag size:          5.2 KiB
Storage id:        mcap
ROS Distro:        jazzy
Duration:          0.000000029s
Start:             Dec 31 1969 18:00:00.000000000 (0.000000000)
End:               Dec 31 1969 18:00:00.000000029 (0.000000029)
Messages:          29 # inconsistent!
Topic information: Topic: /strings | Type: std_msgs/msg/String | Count: 29 | Serialization Format: cdr
Service:           0
Service information:
```

## To Reproduce

1. Collect a bag or generate.
    - Script attached below to generate uncompressed bag used above.
    - Issue has appeared for both real/simulated data.
2. Create yaml used for compression `compressed.yaml`:
```yaml
output_bags:
- uri: compressed-file
  storage_id: mcap
  # storage_id: sqlite3 # storage doesn't seem to affect
  all_topics: true
  all_services: true
  compression_mode: file
  compression_format: zstd
- uri: compressed-message
  storage_id: mcap
  # storage_id: sqlite3 # storage doesn't seem to affect
  all_topics: true
  all_services: true
  compression_mode: message
  compression_format: zstd
```
3. `ros2 bag convert -i uncompressed -o compressed.yaml`
4. `ros2 bag info uncompressed`
5. `ros2 bag info compressed-file`
5. `ros2 bag info compressed-message`

## System
 - OS: Ubuntu Noble
 - ROS 2 Distro: Jazzy
 - Install Method: APT
 - Version: `0.26.6-1noble.20250406.110400`

## Additional context

Script to create uncompressed bag used above.
```python
import rosbag2_py
from rclpy.serialization import serialize_message
from std_msgs.msg import String
writer = rosbag2_py.SequentialWriter()
writer.open(
    rosbag2_py.StorageOptions(uri="uncompressed", storage_id="mcap"),
# rosbag2_py.StorageOptions(uri="uncompressed", storage_id="sqlite3"), # storage doesn't matter either
    rosbag2_py.ConverterOptions(),
)

writer.create_topic(rosbag2_py.TopicMetadata(0, "/strings", "std_msgs/msg/String", "cdr"))

for i in range(30):
    msg_out = String()
    msg_out.data = "Test1"
    writer.write("/strings", serialize_message(msg_out), i)
    # writer.write("/strings", serialize_message(msg_out), 0) # timestamp doesn't seem to matter for this
writer.close()
```

**Comment by MichaelOrlov** [comment]
@DangitBen Can you please try to explicitly setup `compression_queue_size = 0` in your `compressed.yaml` file to see if it will solve the problem?

**Comment by MichaelOrlov** [comment]
Usually, we are dropping messages during compression here
https://github.com/ros2/rosbag2/blob/c712dc24ca54bd65f9836cc3ebd8c11036e94350/rosbag2_compression/src/rosbag2_compression/sequential_compression_writer.cpp#L422-L437

in `compressor_message_queue_.pop(); `

**Comment by DangitBen** [comment]
@MichaelOrlov Yes, that seems to do it! Thank you!

```yaml
output_bags:
- uri: compressed-file
  storage_id: mcap
  all_topics: true
  all_services: true
  compression_mode: file
  compression_format: zstd
  compression_queue_size: 0
- uri: compressed-message
  storage_id: mcap
  all_topics: true
  all_services: true
  compression_mode: message
  compression_format: zstd
  compression_queue_size: 0
```
