### ISSUE TITLE
Humble: ability to use start/end time with bag convert

### ISSUE THREAD

**Issue by andanders** [ros2/rosbag2#2013]
## Description

`ros2 bag convert` has the ability to split the bag by start and end time. Just not in Humble.
And if you use Jazzy to do the conversion that changes the bag so Humble cannot use it.

Example output.yaml
```yaml
output_bags:
- uri: converted
  storage_id: "sqlite3"
  all_topics: true
  start_time_ns: 1747050866000000000
  end_time_ns:   1747050928000000000
```

After converting bag with Jazzy and running `ros2 bag info` or `play` in Humble:
`Exception on parsing info file: yaml-cpp: error at line 15, column 11: bad conversion`
