### ISSUE TITLE
Write QoS metadata YAML as multiline

### ISSUE THREAD

**Issue by emersonknapp** [ros2/rosbag2#609]
## Description

Currently, the `offered_qos_profiles` that are stored in metadata.yaml are stored as a serialized yaml string within the yaml file, e.g.

```
offered_qos_profiles: "- history: 3\n  depth: 0\n  reliability: 1\n  durability: 2\n  deadline:\n    sec: 2147483647\n    nsec: 4294967295\n  lifespan:\n    sec: 2147483647\n    nsec: 4294967295\n  liveliness: 1\n  liveliness_lease_duration:\n    sec: 2147483647\n    nsec: 4294967295\n  avoid_ros_namespace_conventions: false"
```

This would be simpler if it was also serialized and formatted as YAML rather than a string

## Related Issues

N/A

## Completion Criteria

Metadata looks like the following instead:

```
offered_qos_profiles: 
  - history: 3
    depth: 0
    reliability: 1
    durability: 2
    deadline:
      sec: 2147483647
      nsec: 4294967295
    lifespan:
      sec: 2147483647
      nsec: 4294967295
    liveliness: 1
    liveliness_lease_duration:
      sec: 2147483647
      nsec: 4294967295
    avoid_ros_namespace_conventions: false
```

## Implementation Notes / Suggestions

Possibly need to bump the metadata version for this

## Testing Notes / Suggestions

Make sure that both the old string types and the new types are correctly parsed
